### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by tharindu-b-hewage** [tharindu-b-hewage/tharindu-b-hewage.github.io#1]
#### Objectives:

- Sustainable cloud computing
- Practical implementation
- For cloud orchestration, but work closely with operating system

#### Research Problem

- [ ] Identify a venue
    - [ ] Collect top conferences (EuroSys, ATC, NSDI, OSDI, also check FAANG job descriptions)
    - [ ] Filter ones that support student level research (experiments that can be conducted at a reasonable scale, within few months)
    - [ ] Submission deadline in few months, prefer May
    - [ ] Decide on the venue
- [ ] Explore Irene's carbon-aware paper
- [ ] Explore HotCarbon papers
- [ ] Explore Open-source efforts in carbon-aware computing with k8s project
- [ ] Explore similar publications in top confs.
- [ ] Identify the reference paper to built on
- [ ] If reference is not with the selected venue, find another paper from the selected venue to structure experiments and paper writing
- [ ] Identify Gap
- [ ] Formalize,
    - [ ] Application type
    - [ ] Current techniques
    - [ ] Identify state-of-the-art to advance
- [ ] Derive our proposed solution to address the gap -- could be a draft/just insights at this stage
- [ ] Identify deployment
- [ ] Identify workload
- [ ] Implement deployment
- [ ] Inject workload
- [ ] Implement state-of-the-art
- [ ] Experiment with the proposed solution
- [ ] Finalise the proposed solution
- [ ] Design evaluation metrics
- [ ] Design detailed experiments
- [ ] Run and collect data
- [ ] Analyse and evaluate
- [ ] Write the paper
